### ISSUE TITLE
Question about distribution license

### ISSUE THREAD

**Issue by lfcnassif** [lucasgris/wav2vec4bp#2]
First, thank you very much for this fantastic research and work!

I recently read your paper and then find this repo. In our open source project (https://github.com/sepinf-inc/IPED) we have some audio transcription implementations using remote Microsoft and Google services and a local one using Vosk library and models for en/pt-BR.

We are thinking about writing an implementation using your sample code and pre-trained models, since we have to deal with sensitive data from ongoing real world police investigations, so sending data to remote services is a real concern, and our local vosk implementation accuracy is, well, not so good...

So I would like to kindly ask you about the license terms of your sample code and models because I didn't find them. Actually we don't intend to distribute your models directly because they are very big, but to integrate an implementation code (based on your samples) and to point users to your repo so they could download the pre-trained pt-BR models directly from you.

Of course, we will give all credits you deserve for this awesome work!

Thank you in advance!
Luís Nassif

**Comment by lucasgris** [comment]
Thank you, I am glad to help.

I added a LICENSE to the project, you can now use the provided models without any concerns.

I would suggest you to have a look to the models at the [Hugging Face hub](https://huggingface.co/models?language=pt&pipeline_tag=automatic-speech-recognition&sort=downloads), it should be easier to integrate the Hugging Face API with your project. And also, if you need to work with spontaneous speech, I would recommend to use [this model](https://huggingface.co/Edresson/wav2vec2-large-xlsr-coraa-portuguese).

**Comment by lfcnassif** [comment]
Great! Thank you very much for this clarification. And congratulations again for this work!
